name: Render html
on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: addnab/docker-run-action@v3
        with:
          image: toolbelt/mustache
          options: -v ${{ github.workspace }}:/work --user 0:0
          run: |
            cat /work/hash.json | mustache - /work/template-index.html > /work/public/index.html
      - name: Create release archive
        run: tar -C ./public -czf ./release.tar.gz .
      - id: tag_version
        name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          artifacts: release.tar.gz