name: Render html
on:
  push

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - id: template
        name: Render html using mustache
        uses: recih/template-render-action@v1
        with:
          engine: mustache
          template-file: ./template-index.html
          vars: hash.json
          output-file: public/index.html
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}