name: Render html
on:
  push

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - id: template
        name: Render html using mustache
        uses: recih/template-render-action@v1
        with:
          engine: mustache
          template-file: ./template-index.html
          vars: hash.json
          output-file: public/index.html
      - id: release_archive
        name: Create release archive
        run: tar czf release.tar.gz ./public
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          artifacts: release.tar.gz